### ISSUE TITLE
do java11 support?  serial  related  datasource don't run normally base java11

### ISSUE THREAD

**Issue by huanghe-1** [MangoAutomation/ma-core-public#1670]

**Comment by jazdw** [comment]
Yes Java 11 is supported. We will need more details if you are having problems. What is going wrong? Are there error messages in your ma.log file?

**Comment by huanghe-1** [comment]
java 11, serial related datasource,for example, modbus_serial ,when start  ma-start.bat, the form  flash across,error log in attach.
[hs_err_pid13320.log](https://github.com/infiniteautomation/ma-core-public/files/5664626/hs_err_pid13320.log)
and change to java 8, it is ok.

**Comment by huanghe-1** [comment]
that is  jssc problem，update jssc  is ok.
